# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-07 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinax_notifications', '0002_auto_20171003_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.CharField(choices=[(b'0', 'E-mailov\xe9'), (b'1', 'V ZANETu')], max_length=1, verbose_name='medium'),
        ),
        migrations.AlterUniqueTogether(
            name='noticesetting',
            unique_together=set([('user', 'notice_type', 'medium')]),
        ),
    ]
