# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0003_notice_settings_constraint_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.CharField(choices=[(b'0', 'email')], max_length=1, verbose_name='medium'),
        ),
    ]
